name: kubernator
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.10.0-rc.2'
          - '3.9'
    env:
      DEPLOY_PYTHONS: "3.9"
      DEPLOY_OSES: "Linux"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
    steps:
      - name: Should Upload
        if: |
          github.event_name == 'push' &&
          contains(env.DEPLOY_OSES, runner.os) &&
          contains(env.DEPLOY_PYTHONS, matrix.python-version)
        shell: bash
        run: echo "PYB_EXTRA_ARGS=+upload" >> "$GITHUB_ENV"
      - name: Build with PyBuilder
        uses: pybuilder/build@master
        with:
          python-version: ${{ matrix.python-version }}
          pyb-extra-args: ${{ env.PYB_EXTRA_ARGS }}
  build-summary:
    if: success() || failure()
    runs-on: ubuntu-latest
    name: Build Stable Summary
    needs: build
    steps:
      - name: Check build matrix status
        if: needs.build.result != 'success'
        run: exit 1
